version: 2
jobs:
        build:
                docker:
                        - image: debian:stretch
                steps:
                        - run:
                                name: Greeting
                                command: echo "Hello, world: $TEST_NULL"
                        - run: 
                                name: Base64
                                command: echo "Hello, world: $TEST_NULL" | base64 -

        print_date:
                docker:
                        - image: debian:stretch
                steps:
                        - run:
                                name: Print current time
                                command: date

workflows:
        version: 2
        build_stuff:
                jobs:
                        - build:
                                context: test-cli
                        - hold:
                                type: approval
                                requires:
                                        - build
                        - print_date:
                                requires:
                                        - hold
